(source gnu)
;; (source melpa-stable)
(source melpa)

(depends-on "cask")
(depends-on "dash")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "multiple-cursors")
(depends-on "s")
(depends-on "yasnippet")
(depends-on "exec-path-from-shell") ;; init PATH in emacs shell
(depends-on "yaml-mode")
(depends-on "markdown-mode")
(depends-on "feature-mode")
(depends-on "terraform-mode")
(depends-on "2048-game")
(depends-on "sr-speedbar") ;; speedbar navigation within current frame
(depends-on "project-explorer") ;; source navigation
(depends-on "anzu") ;; shows a count of search matches in the mode-line
(depends-on "goto-chg") ;; an easy way to jump to my last edit
(depends-on "fullframe") ;; display next command in full frame
(depends-on "haskell-mode")
(depends-on "smartparens") ;; deals with pairs
(depends-on "perspective")
(depends-on "persp-projectile")
(depends-on "which-key")

;; editing
(depends-on "aggressive-indent")

;; git
(depends-on "magit")
(depends-on "magit-gh-pulls")

;; themes
(depends-on "monokai-theme")

;; helm
(depends-on "helm")
(depends-on "helm-dash")
(depends-on "helm-ag")
(depends-on "helm-descbinds")

;; projectile
(depends-on "projectile")
(depends-on "projectile-speedbar")
(depends-on "helm-projectile")

;; auto completion
(depends-on "auto-complete")
(depends-on "ac-helm")

;; ruby mode
(depends-on "robe")
(depends-on "rvm")
(depends-on "rubocop")
(depends-on "ruby-refactor")
(depends-on "ruby-hash-syntax")
(depends-on "ruby-tools")
(depends-on "ruby-guard")
(depends-on "ruby-end")
(depends-on "rspec-mode")
(depends-on "bundler")

;; elixir
(depends-on "elixir-mode")
(depends-on "alchemist")

;; (depends-on "whitespace") ;; display whitespace marks
;; (depends-on "discover") ;; an easy way to learn more about Emacs

;; web mode
(depends-on "coffee-mode")
(depends-on "haml-mode")
(depends-on "css-mode")
(depends-on "web-mode")
(depends-on "json-mode")
